### ISSUE TITLE
Selección de documentos relativos al TFG que serán considerados

### ISSUE THREAD

**Issue by jrg1013** [jrg1013/chatbot#14]
**Objetivo:**
El propósito de esta Issue es abordar el proceso de selección de documentos relevantes y apropiados que se utilizarán como fuentes de información en las técnicas de "Retrieval-augmented Generation" (RAG) para enriquecer las respuestas del chatbot.

**Contexto:**
Para garantizar que el chatbot pueda proporcionar respuestas precisas y contextualmente relevantes a las preguntas de los estudiantes, es esencial determinar qué documentos deben ser considerados para la recuperación de información. Estos documentos pueden incluir tesis previas, recursos académicos, guías de PFG, entre otros.

**Tareas:**
- Identificar fuentes de información relevantes que puedan servir como documentos para el RAG.
- Evaluar la calidad y actualidad de los documentos seleccionados.
- Determinar un método para la incorporación y actualización constante de nuevos documentos relevantes en la base de datos de RAG.

**Criterios de Éxito:**
- Seleccionar una variedad de documentos que abarquen diversos aspectos relacionados con la realización de TFGs en Ingeniería Informática.
- Establecer un proceso eficiente y escalable para mantener actualizada la base de datos de documentos.
- Garantizar que los documentos seleccionados sean apropiados y relevantes para las necesidades de los estudiantes que buscan asistencia en sus TFGs.

**Comment by clopezno** [comment]
Registro de Question/Answer de las FAQ para TFG online  https://github.com/aav0038/UBU-CHATBOT/blob/master/chatbotOnline/Listado%20Preguntas-Respuestas%20-%20ONLINE.docx

**Comment by clopezno** [comment]
Histórico de tfg presentados en la asignatura gii ONLINE https://clopezno.github.io/tfg_gii_online/HistoricoSist.html

Por  cada tfg registrado puede tener registrado:
- Acceso a su repositorio público Github o Gitlab (readme, memoria Latex, issues, releases)
- Vídeos de presentación y defensa
- Enlaces a herramientas de auditoría de calidad de código
